Add nonstd-span-lite 0.5.0 release
mesonbuild/nonstd-span-lite pull request #1
Opened 2019-09-03 08:05 UTC by mattyclarkson

How do I test this before we merge?

When this merges, I'll add all the other `nonstd-*` in a similar fashion.

2019-09-04 10:45 UTC, mattyclarkson commented
@sarum9in, RFC

2019-09-16 15:57 UTC, mattyclarkson commented
@sarum9in what do you think? Could we get this in as a first step?

2019-09-17 11:21 UTC, sarum9in requested changes

2019-09-17 11:21 UTC, sarum9in commented on upstream.wrap
> +directory = nonstd-span-lite-0.5.0
It seems like the directory name is `span-lite-0.5.0` according to
```
$ tar tf v0.5.0 
span-lite-0.5.0/
...
```

2019-09-23 08:49 UTC, mattyclarkson commented on upstream.wrap
> +directory = nonstd-span-lite-0.5.0
Thanks! I actually thought that determined what folder the wrap unpacked into. Thanks for the clarification :smile:

2019-09-30 17:04 UTC, merged